---
- name: installing required packages
  hosts: webservers:appservers
  become: true

  tasks:
  - name: Install the latest version of Apache
    ansible.builtin.yum:
      name: httpd
      state: latest