---
- name: Update web servers
  hosts: webservers:appserver
  become: true
  vars_files: 
    - user-details.yml

  tasks:
  - name: creating user 
    ansible.builtin.user:
      name: "{{user}}"
      comment: don de don